import { QuoteCatalogItem, QuoteService, ZoneTier } from './types'

export const quoteServices: QuoteService[] = [
  {
    id: 'diagnostico-electrico',
    name: 'Diagnóstico eléctrico',
    description: 'Inspección técnica inicial con mediciones y recomendaciones claras.',
    flow: 'ONLINE',
    path: 'PUNTUAL',
    basePrice: 95000,
    minPrice: 95000,
    includes: ['Revisión técnica', 'Mediciones básicas', 'Informe digital'],
    excludes: ['Materiales y reparaciones'],
  },
  {
    id: 'reparacion-falla',
    name: 'Reparación de falla eléctrica',
    description: 'Resolución de cortes, saltos de térmica o fallas puntuales del circuito.',
    flow: 'ONLINE',
    path: 'PUNTUAL',
    basePrice: 120000,
    minPrice: 120000,
    includes: ['Búsqueda de falla', 'Reparación puntual', 'Prueba de funcionamiento'],
    excludes: ['Recableado integral'],
  },
  {
    id: 'colocacion-artefactos',
    name: 'Colocación de artefactos',
    description: 'Instalación y conexión de luminarias, ventiladores y artefactos eléctricos.',
    flow: 'ONLINE',
    path: 'PUNTUAL',
    basePrice: 75000,
    minPrice: 75000,
    includes: ['Montaje', 'Conexión', 'Prueba funcional'],
    excludes: ['Artefactos no provistos'],
  },
  {
    id: 'circuito-dedicado-aa',
    name: 'Circuito dedicado para aire acondicionado',
    description: 'Línea independiente y protecciones según consumo del equipo.',
    flow: 'ONLINE',
    path: 'PUNTUAL',
    basePrice: 180000,
    minPrice: 180000,
    includes: ['Circuito dedicado', 'Protecciones', 'Verificación final'],
    excludes: ['Equipo de aire'],
  },
  {
    id: 'adecuacion-tablero',
    name: 'Adecuación básica de tablero',
    description: 'Orden, ajuste y mejoras básicas para llevar el tablero a condición segura.',
    flow: 'ONLINE',
    path: 'PUNTUAL',
    basePrice: 160000,
    minPrice: 160000,
    includes: ['Ajuste de protecciones', 'Orden básico', 'Checklist de seguridad'],
    excludes: ['Cambio total de tablero'],
  },
  {
    id: 'revision-general',
    name: 'Revisión eléctrica general',
    description: 'Chequeo completo del estado eléctrico de vivienda, local u oficina.',
    flow: 'ONLINE',
    path: 'PUNTUAL',
    basePrice: 110000,
    minPrice: 110000,
    includes: ['Inspección general', 'Detección de riesgos', 'Recomendaciones'],
    excludes: ['Trabajos correctivos'],
  },
  {
    id: 'cambio-tomas',
    name: 'Cambio de tomas / teclas / llaves',
    description: 'Reemplazo y adecuación de puntos de uso eléctrico deteriorados.',
    flow: 'ONLINE',
    path: 'PUNTUAL',
    basePrice: 68000,
    minPrice: 68000,
    includes: ['Recambio de piezas', 'Conexión y ajuste', 'Prueba'],
    excludes: ['Materiales especiales'],
  },
  {
    id: 'iluminacion-interior-exterior',
    name: 'Iluminación interior / exterior',
    description: 'Instalación y mejora de iluminación para espacios internos y externos.',
    flow: 'ONLINE',
    path: 'PUNTUAL',
    basePrice: 130000,
    minPrice: 130000,
    includes: ['Definición rápida de puntos', 'Instalación', 'Pruebas'],
    excludes: ['Obra civil adicional'],
  },
  {
    id: 'visita-tecnica',
    name: 'Visita técnica',
    description: 'Visita para evaluar el trabajo y definir próximos pasos en sitio.',
    flow: 'ONLINE',
    path: 'PUNTUAL',
    basePrice: 70000,
    minPrice: 70000,
    includes: ['Visita', 'Diagnóstico inicial', 'Recomendación de alcance'],
    excludes: ['Ejecución en la misma visita'],
  },
  {
    id: 'reforma-parcial',
    name: 'Reforma eléctrica parcial',
    description: 'Actualización por sectores con definición técnica previa.',
    flow: 'SURVEY',
    path: 'OBRA',
    basePrice: 320000,
    includes: ['Visita técnica', 'Alcance por etapas', 'Presupuesto inicial'],
    excludes: ['Ejecución sin validación'],
  },
  {
    id: 'instalacion-local-oficina',
    name: 'Instalación para local u oficina',
    description: 'Instalaciones eléctricas para comercios y espacios de trabajo.',
    flow: 'SURVEY',
    path: 'OBRA',
    basePrice: 540000,
    includes: ['Relevamiento', 'Propuesta técnica', 'Plan de obra'],
    excludes: ['Ingeniería externa de terceros'],
  },
  {
    id: 'instalacion-vivienda-integral',
    name: 'Instalación integral de vivienda',
    description: 'Instalación completa para obra nueva o reforma integral de vivienda.',
    flow: 'SURVEY',
    path: 'OBRA',
    basePrice: 860000,
    includes: ['Definición técnica', 'Estimación por etapas', 'Planificación'],
    excludes: ['Materiales fuera de acuerdo'],
  },
  {
    id: 'obra-comercial',
    name: 'Obra comercial',
    description: 'Ejecución eléctrica para proyectos comerciales de mayor escala.',
    flow: 'SURVEY',
    path: 'OBRA',
    basePrice: 920000,
    includes: ['Relevamiento', 'Plan técnico', 'Cronograma general'],
    excludes: ['Trámites municipales'],
  },
  {
    id: 'mantenimiento-programado',
    name: 'Mantenimiento técnico programado',
    description: 'Servicio periódico para garantizar continuidad y seguridad eléctrica.',
    flow: 'SURVEY',
    path: 'OBRA',
    basePrice: 420000,
    includes: ['Rutinas programadas', 'Informes', 'Plan de corrección'],
    excludes: ['Reformas fuera del alcance mensual'],
  },
  {
    id: 'otros-relevamiento',
    name: 'Otros trabajos con relevamiento',
    description: 'Si tu trabajo no encaja en los anteriores, lo definimos con visita técnica.',
    flow: 'SURVEY',
    path: 'OBRA',
    basePrice: 300000,
    includes: ['Visita técnica', 'Definición de alcance', 'Presupuesto base'],
    excludes: ['Ejecución sin validación'],
  },
]

export const professionalCatalog: QuoteCatalogItem[] = [
  { id: 'boca-iluminacion', name: 'Bocas de iluminación', unit: 'boca', baseUnitPrice: 26000, kind: 'PER_POINT', suggestedQty: 12 },
  { id: 'tomacorriente', name: 'Tomacorrientes', unit: 'boca', baseUnitPrice: 30000, kind: 'PER_POINT', suggestedQty: 10 },
  { id: 'boca-especial', name: 'Bocas especiales', unit: 'boca', baseUnitPrice: 42000, kind: 'PER_POINT', suggestedQty: 4 },
  { id: 'boca-datos', name: 'Bocas de datos', unit: 'boca', baseUnitPrice: 31000, kind: 'PER_POINT', suggestedQty: 4 },
  { id: 'boca-aa', name: 'Bocas de aire acondicionado', unit: 'boca', baseUnitPrice: 49000, kind: 'PER_POINT', suggestedQty: 3 },
  { id: 'tablero', name: 'Tableros', unit: 'unidad', baseUnitPrice: 280000, kind: 'UNIT', suggestedQty: 1 },
  { id: 'puesta-tierra', name: 'Puesta a tierra', unit: 'unidad', baseUnitPrice: 180000, kind: 'UNIT', suggestedQty: 1 },
  { id: 'canalizacion', name: 'Canalizaciones', unit: 'ml', baseUnitPrice: 22000, kind: 'UNIT', suggestedQty: 40 },
]

type ZoneDefinition = {
  tier: ZoneTier
  label: string
  maxDistanceKm: number
}

export const zoneDefinitions: ZoneDefinition[] = [
  { tier: 'PRIORITY', label: 'Prioritaria', maxDistanceKm: 8 },
  { tier: 'STANDARD', label: 'Estándar', maxDistanceKm: 18 },
  { tier: 'EXTENDED', label: 'Extendida', maxDistanceKm: 34 },
]
